Move  execution listener to a separate module
togglz/togglz pull request #1002
Opened 2023-04-12 14:23 UTC by hantsy

fixes #997

2023-05-24 14:21 UTC, hantsy commented
@bennetelli I tried to add a test for the test execution listener, but I am not sure I could add more assertions to verify the operation in the `TogglzTestExecutionListener`.

2023-05-30 11:39 UTC, bennetelli requested changes

2023-05-30 13:22 UTC, bennetelli commented on .github/workflows/maven.yml
> +        run: mvn -B verify -Pwildfly-managed
ah thanks! I thought it would be an option provided by the wildfly maven plugin. Thanks for the explanation

2023-05-31 13:49 UTC, bennetelli requested changes
I thought about this once again. IMO it would be better to integrate it in the existing spring boot starters instead of having to add the starter and the spring-test dependency to every project.

In the end there should be the spring-boot-starter only if it is possible.

2023-06-02 07:09 UTC, bennetelli commented
I think we need to find a better way to achieve this. With these changes, projects using togglz with Feature enum would not need to add the new spring-test dependency, but projects using the application.yml file to declare their feature toggles would need to do it. 

IMO that should be hidden for the users and they should not have to add an additional dependency in this case.

2023-07-29 09:42 UTC, closed without merging

2023-07-29 09:43 UTC, hantsy commented
We gave up this in projects.